version: "3.7"
services:
  cxflow-webhook:
    build:
      context: cxflow-docker
    environment:
      JAVA_OPTS: ${JAVA_OPTS:-}
      CXFLOW_MODE: ${CXFLOW_MODE:-web}
      CX_CONFIG: ${CX_CONFIG:-general}
      CXFLOW_PORT: ${CXFLOW_PORT:-8585}
      CXFLOW_DEBUG_PORT: ${CXFLOW_DEBUG_PORT:-1044}
    ports:
      - "${CXFLOW_PORT:-8585}:${CXFLOW_PORT:-8585}"
      - "${CXFLOW_DEBUG_PORT:-1044}:${CXFLOW_DEBUG_PORT:-1044}"
    dns:
      - 8.8.8.8
    restart: "no"

