version: "3.7"
services:
  cxflow-webhook:
    build:
      context: cxflow-docker
    depends_on: 
      - jira-server
    environment:
      JAVA_OPTS: ${JAVA_OPTS:-}
      CXFLOW_MODE: ${CXFLOW_MODE:-web}
      CX_CONFIG: ${CX_CONFIG:-general}
      CXFLOW_PORT: ${CXFLOW_PORT:-8585}
      CXFLOW_DEBUG_PORT: ${CXFLOW_DEBUG_PORT:-1044}
    ports:
      - "${CXFLOW_PORT:-8585}:${CXFLOW_PORT:-8585}"
      - "${CXFLOW_DEBUG_PORT:-1044}:${CXFLOW_DEBUG_PORT:-1044}"
    dns:
      - 8.8.8.8
    restart: "no"


  jira-server:
    image: atlassian/jira-software:latest
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    dns:
      - 8.8.8.8
    ports:
      - "${JIRA_PORT:-8000}:8080"
    restart: "no"

volumes:
  jira_data:


